
parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: tknikabackups
    database_user: root
    database_password: root
    mailer_transport: gmail
    mailer_host: localhost
    mailer_user: tknikabackups
    mailer_password: n6dC4P9w
    locale: en
    secret: fba546d6ab6abc4a01391d161772a14e093c7aa2
    database_path: null
    upload_dir: /srv/web/tknikabackups-devel/uploaded
    backup_dir: /srv/web/tknikabackups-devel/backups
    public_key: /home/www-data/.ssh/id_rsa.pub
    max_log_age: P1Y
    tmp_dir: /srv/web/tknikabackups-devel/tmp
    rsnapshot: /usr/bin/rsnapshot
    warning_load_level: 0.8
    pagination_lines_per_page: 20
