binovo_tknika_tknika_backups:
    resource: "@BinovoTknikaTknikaBackupsBundle/Controller/"
    type:     annotation
    prefix:   /
login_check:
    pattern:   /login_check
logout:
    pattern: /logout
