jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Binovo\Tknika\TknikaBackupsBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        administrators:
            entity: { class: BinovoTknikaTknikaBackupsBundle:User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js|setlocale)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                check_path: /login_check
                login_path: /login
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/login,         roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/user,          roles: ROLE_ADMIN}
        - { path: ^/users,         roles: ROLE_ADMIN}
        - { path: ^/config/params, roles: ROLE_ADMIN}
        - { path: ^/,              roles: ROLE_USER}
